services:
  db:
    image: mysql:8.0.31
    container_name: ave-db
    volumes:
      - mysql_data:/var/lib/mysql/
      - ./db/my.cnf:/etc/mysql/my.cnf
      - ./db:/docker-entrypoint-initdb.d
    env_file:
      - db.env
    restart:
      unless-stopped

  web:
    build:
      context: ./web
      args:
        DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    container_name: ave-web
    ports:
      - "9000:9000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - web.env
    command: bash -c "python manage.py collectstatic --no-input && daphne -v 1 -b 0.0.0.0 -p 9000 photo_blog.asgi:application"
    depends_on:
      - db
    restart:
      unless-stopped

volumes:
  mysql_data:
  static_volume:
  media_volume:
  certs: