version: "3.9"

services:
  nginx:
    build: ./nginx
    container_name: ave-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      IP_ADDR: ${IP_ADDR}
    restart:
      unless-stopped
    depends_on:
      - web
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./certs:/etc/ssl/certs

  db:
    image: mysql:5.7.36
    container_name: ave-db
    volumes:
      - mysql_data:/var/lib/mysql/
    env_file:
      - db.env
    restart:
      unless-stopped

  web:
    build: ./web
    container_name: ave-web
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - web.env
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && daphne -b 0.0.0.0 -p 9000 photo_blog.asgi:application"
    depends_on:
      - db
    restart:
      unless-stopped

volumes:
  mysql_data:
  static_volume:
  media_volume: