# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 03:28
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170102_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(max_length=255)),), classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(classname='paragraph', requeried=True)), ('code_chunk', wagtail.wagtailcore.blocks.StructBlock((('code', wagtail.wagtailcore.blocks.TextBlock(blank=False, max_length=8000, null=False)), ('language', wagtail.wagtailcore.blocks.ChoiceBlock(blank=False, choices=[('Python', 'CSS', 'HTTP', 'JavaScript', 'Bash', 'Ini', 'SQL', 'JSON', 'Markdown', 'HTML', 'XML', 'Java', 'Nginx')], default='Python', null=False)))))), verbose_name='body'),
        ),
    ]
