# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 03:29
from __future__ import unicode_literals

from django.db import migrations, models
from wagtail.wagtailcore.rich_text import RichText


def convert_to_streamfield(apps, schema_editor):
    BlogPage = apps.get_model('blog', 'BlogPage')
    for page in BlogPage.objects.all():
        if page.body.raw_text and not page.body:
            page.body = [('paragraph', RichText([page.body.paragraph]))]
            page.save()


def convert_to_richtext(apps, schema_editor):
    BlogPage = apps.get_model('blog', 'BlogPage')
    for page in BlogPage.objects.all():
        if page.body.paragraph is None:
            paragraph = ''.join([
                child.value.source for child in page.body
                if child.block_type == 'pagegraph'
            ])
            page.body = paragraph
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170116_2028'),
    ]

    operations = [
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext,
        ),
    ]
