# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 05:31
from __future__ import unicode_literals

import blog.models
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170116_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', blog.models.Heading(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock(classname='paragraph', requeried=True)), ('code_chunk', wagtail.wagtailcore.blocks.StructBlock((('code', wagtail.wagtailcore.blocks.TextBlock(blank=False, max_length=8000, null=False)), ('language', wagtail.wagtailcore.blocks.ChoiceBlock(blank=False, choices=[('python', 'Python'), ('css', 'CSS'), ('http', 'HTTP'), ('javascript', 'JavaScript'), ('bash', 'Bash'), ('ini', 'Ini'), ('sql', 'SQL'), ('json', 'JSON'), ('markdown', 'Markdown'), ('html', 'HTML'), ('xml', 'XML'), ('java', 'Java'), ('nginx', 'Nginx')], default='Python', null=False)))))), verbose_name='body'),
        ),
    ]
