# Generated by Django 3.0.3 on 2020-02-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200204_1412'),
        ('blog', '0007_auto_20180617_2036'),
    ]

    operations = [
    ]
