# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-18 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180103_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='This date is displayed on the blog post. It is not used to schedule posts to go live at a later date.', verbose_name='Post date'),
        ),
    ]
