# Generated by Django 3.2.18 on 2023-04-26 00:38

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail_photography.blocks
import wagtail_photography.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('gallery', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('collection', wagtail_photography.blocks.CollectionChooserBlock())]))], blank=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_photography.models.PhotoGalleryMixin, 'wagtailcore.page'),
        ),
    ]
